# Generated by Django 3.0.2 on 2020-02-17 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0003_auto_20200217_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 17, 22, 17, 3, 580952)),
        ),
    ]
