# Generated by Django 3.0.2 on 2020-02-18 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0005_auto_20200218_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 18, 9, 9, 51, 955716)),
        ),
    ]
