# Generated by Django 3.0.2 on 2020-02-26 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0006_auto_20200218_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 26, 9, 21, 59, 909664)),
        ),
    ]
