# Generated by Django 3.0.2 on 2020-02-27 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0007_auto_20200226_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 27, 17, 21, 47, 206570)),
        ),
    ]
