# Generated by Django 3.0.2 on 2020-03-03 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0009_auto_20200303_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 3, 19, 38, 9, 363608)),
        ),
    ]
