# Generated by Django 3.0.2 on 2020-03-03 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0011_auto_20200303_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 3, 22, 36, 17, 430548)),
        ),
    ]
