# Generated by Django 3.0.2 on 2020-03-09 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0013_auto_20200304_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 9, 21, 55, 19, 588280)),
        ),
    ]
