# Generated by Django 3.0.2 on 2020-03-14 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0014_auto_20200309_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 21, 47, 53, 669867)),
        ),
    ]
