# Generated by Django 3.0.2 on 2020-03-15 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistic', '0015_auto_20200314_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 15, 8, 41, 14, 635895)),
        ),
    ]
