# Generated by Django 3.0.2 on 2020-02-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_num',
        ),
    ]
