# Generated by Django 3.0.2 on 2020-03-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_grade_paper_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_time',
            field=models.DateField(default='1970-01-01', verbose_name='签到时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
